FROM ubuntu:18.04
MAINTAINER Marathon Speedrun Developers

RUN apt update
RUN apt install -y openjdk-8-jdk build-essential libboost-all-dev libexpat-dev libsdl2-dev libsdl2-image-dev libsdl2-net-dev libsdl2-ttf-dev libsdl2-mixer-dev libspeexdsp-dev libzzip-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libpng-dev libcurl4-gnutls-dev wget git autoconf automake
